### ISSUE TITLE
Add to nimble package list?

### ISSUE THREAD

**Issue by Jeff-Ciesielski** [flaviut/nimrun#7]
IIRC, nimble includes the option of deploying executables.  Might be nice to have this as a nimble package so that it integrates nicely with the ecosystem.

**Comment by flaviut** [comment]
That's a good idea! Looks like nimble requires that the executable be compiled from a nim source file though, so this script will need to be re-written in Nim (or a wrapper written in Nim).

**Comment by Jeff-Ciesielski** [comment]
I hope you don't mind, but I actually went ahead and ported this to nim: https://github.com/Jeff-Ciesielski/nimr (I gave you credit in the readme).

There are actually a few of these floating around now and there was some discussion about adding a `-s` option to the nim compiler to run things as a script with sane defaults.

**Comment by flaviut** [comment]
Awesome! A couple small suggestions: don't use string interpolation in the
command. Pass an array of arguments​ (or escape filenames), it's more
reliable with unusual filenames; and in the case of zero args, print a help
message.
